config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  get 'users/:id/logout', to: 'users#logout'

  resources :users, only: [:show]
  resources :cards, only: [:new, :create, :destroy, :show]

  root to: 'messages#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: [:new, :create]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @items_category = Item.includes(:images).order('created_at DESC').limit(4)
    @items_brand = Item.includes(:images).order('created_at DESC').limit(4).where.not(brand: "")
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.haml
= render "items/header"
.main
  %section.mainVisual
    .mainVisual__content
      %h2.mainVisual__content__subtitle
        %br/
        人生を変えるフリマアプリ
      %p.mainVisual__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .mainVisual__content__btn
        = link_to image_tag("pict/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"aBtn"), "/"
        = link_to image_tag("pict/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"gBtn"), "/"
  %section.mainExplanation
    %h2.mainExplanation__subtitle
      FURIMAが選ばれる3つの理由
    %ul.mainExplanation__lists
      %li.list
        .list__pict
          %span.number 1
          = image_tag "pict/pict-reason-01.jpg"
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number 2
          = image_tag "pict/pict-reason-02.jpg"
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pict
          %span.number 3
          = image_tag "pict/pict-reason-03.jpg"
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&amp;購入！
  %section.mainMiddle
    .mainMiddle__inner
      %h2.mainMiddle__inner__subtitle 会員数日本一位
      %p.mainMiddle__inner__text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .mainMiddle__inner__btn
        = link_to image_tag("pict/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"aBtn"), "/"
        = link_to image_tag("pict/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"gBtn"), "/"
  %section.mainFeatures
    %h2.mainFeatures__head
      FURIMAの特徴
    .items
      %section.item
        %figure.item__img
          = image_tag "icon/icon-01.png"
        %h3.item__subtitle 簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.item
        %figure.item__img
          = image_tag "icon/icon-03.png"
        %h3.item__subtitle 売上金は即日振込みに対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %section.item
        %figure.item__img
          = image_tag "icon/icon-04.png"
        %h3.item__subtitle 様々な支払いに対応
        %p.item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.mainPickup
    %h2.mainPickup__head ピックアップカテゴリー
    .productBox
      .productHead
        = link_to "#" do
          %h3.title 新規投稿商品
      .productLists
        - @items_category.each_with_index do |item, n|
          .productList
            %figure.productList__img
              = link_to item_path(item) do
                = image_tag item.images.first.src.url, size:'220x150'
            .productList__body
              %h3.name
              = item.name[0,10]
              - if item.name.size > 9
                = "..."
              .details
                %ul
                  %li
                    = number_to_currency(item.price)
                  %li
                    - if item.trading_status == "syuppintyu"
                      .item__sale__blue
                        出品中
                    - else
                      .item__sale__red
                        売却済
                %p (税込)

  %section.mainPickup
    %h2.mainPickup__head ピックアップブランド
    .productBox
      .productHead
        = link_to "#" do
          %h3.title アーカイバ
      .productLists
        - @items_brand.each_with_index do |item, n|
          .productList
            =link_to ""
            %figure.productList__img
              = link_to item_path(item) do
                = image_tag item.images.first.src.url, size:'220x150'
            .productList__body
              %h3.name 
                = item.name[0,10]
                - if item.name.size > 9
                  = "..."
              .details
                %ul
                  %li 
                    = number_to_currency(item.price)
                  %li
                    - if item.trading_status == "syuppintyu"
                      .item__sale__blue
                        出品中
                    - else
                      .item__sale__red
                        売却済 
                %p (税込)
  
  %section.mainBanner
    .inner
      %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text 今すぐ無料ダウンロード！
      .inner__icon
        = link_to image_tag("pict/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"aBtn"), "/"
        = link_to image_tag("pict/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"gBtn"), "/"
= render "items/footer"


.fotter__Btn{style: ""}
  - if user_signed_in?
    = link_to new_item_path, class: "btn" do
      %span.fotter__Btn__text 出品する
      = image_tag "icon/icon_camera.png", class: "fotter__Btn__icon"
  - else
    = link_to new_user_session_path, class: "btn" do
      %span.fotter__Btn__text 出品する
      = image_tag "icon/icon_camera.png", class: "fotter__Btn__icon"