config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  get 'users/:id/logout', to: 'users#logout'

  resources :users, only: [:show]
  resources :cards, only: [:new, :create, :destroy, :show]

  root to: 'messages#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: [:new, :create]
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require "payjp"
   before_action :set_item

  def new
  end

  def create
    if current_user.card.nil?
      redirect_to new_card_path, alert: "クレジットカード情報を登録してください"
    else
      @purchase = Purchase.new
      @purchase.item_id = @item.id
      @purchase.user_id = current_user.id
      @purchase.save
      @item.trading_status = 2
      @item.save
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
      Payjp::Charge.create(
        amount: @item.price,
        customer: current_user.card.customer_id,
        currency: 'jpy'
      )
      redirect_to root_path, notice: "購入が完了しました"
    end
  end

  private

  def purchase_params
    params.require(:purchase).merge(user_id: current_user.id, item_id: params[:item_id])
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/views/purchases/new.html.haml
= render "devise/shared/header"
.purchase
  .purchase__content
    .purchase__content__top
      購入内容の確認
    .purchase__content__bottom
      .purchase__content__bottom__center
        .purchase__content__bottom__center__left
          = image_tag @item.images[0].src.url, size:'120x110'
        .purchase__content__bottom__center__right
          .purchase__content__bottom__center__right__name
            = @item.name
          .purchase__content__bottom__center__right__price
            (税込)
            = "¥#{@item.price.to_s(:delimited, delimiter: ",")}"
      .purchase__content__bottom__pay
        .purchase__content__bottom__pay__name
          支払い金額
        .purchase__content__bottom__pay__price
          = "¥#{@item.price.to_s(:delimited, delimiter: ",")}"
    - if user_signed_in?
      .purchase__content__bottom__submit
        = link_to "購入する", item_purchases_path(@item), method: :post, class: "purchase__content__bottom__submit__buy"
    - else
      .purchase__content__bottom__submit
        = link_to "購入する",  new_user_session_path, class: "purchase__content__bottom__submit__buy"
= render "devise/shared/footer"