config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  get 'users/:id/logout', to: 'users#logout'

  resources :users, only: [:show]
  resources :cards, only: [:new, :create, :destroy, :show]

  root to: 'messages#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: [:new, :create]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  
  has_many :images , dependent: :destroy
  belongs_to :user
  belongs_to :category
  has_many :purchases

  validates :name, :price, :description, :status, :cost, :day, :prefecture_id, :category, :user, presence: true

  validates_associated :images
  validates :images, presence: {message: "を最低1枚選択してください"}

  validates_numericality_of :price, message: "は半角数字を入力してください"

  validates :price, numericality: { greater_than_or_equal_to: 300, message: "は300円以上にしてください" }
  validates :price, numericality: { less_than_or_equal_to: 9999999, message: "は9,999,999円以下にしてください" }
  validates :trading_status, numericality: { egreater_than_or_equal_to: 1}

  accepts_nested_attributes_for :images, allow_destroy: true

  # 商品の状態
  enum status: {
    sentaku:0,
    sinpin:1,
    misiyou:2,
    yogorenasi:3,
    yayakizuari:4,
    kizuari:5,
    zyoutaigawarui:6,
  }, _prefix:true
  validates :status,
  format: {with: /\A(?!sentaku)/ , message: "を選択してください"}

  # 出品状況
  enum trading_status: {
    sentaku:0,
    syuppintyu:1,
    baikyakuzumi:2,
  }

  # 配送料の負担
  enum cost: {
    sentaku:0,
    souryoukomi:1,
    tyakubarai:2,
  }, _prefix:true
  validates :cost,
  format: {with: /\A(?!sentaku)/ , message: "を選択してください"}

  # 発送までの日数
  enum day: {
    sentaku:0,
    itiniti:1,
    futuka:2,
    yokka:3,
  }, _prefix:true
  validates :day,
  format: {with: /\A(?!sentaku)/ , message: "を選択してください"}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_items, only: [:edit, :update, :destroy, :show]
  before_action :set_category, only: [:edit, :update]
  before_action :set_category_child, only: [:edit, :update]
  before_action :set_category_grandchild, only: [:edit, :update]
  before_action :set_category_id, only: [:edit, :update]
  before_action :set_product, except: [@products, :index, :new, :create, :show, :edit, :update, :destroy, :get_category_children,:get_category_grandchildren]

  def new
    @category_parent_array =  Category.where(ancestry: nil)    
    @item = Item.new
    @item.images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @category_parent_array =  Category.where(ancestry: nil)
      @item.images = []
      @item.images.new
      render action: :new
    end
  end

  def edit
    @category_parent_array =  Category.where(ancestry: nil)
    @item.images.new
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render action: :edit
    end
  end

  def show
    @user = User.find(@item.user_id)
    @category = Category.find(params[:id])
  end

  def destroy
    if current_user.id == @item.user_id && @item.destroy
      redirect_to root_path, notice: "削除しました"
    else 
      render action: :show, alert: "削除に失敗しました"
    end
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: params[:parent_name]).children
  end

 # 子カテゴリーが選択された後に動くアクション
 def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
 end

  private
  def item_params
    params.require(:item).permit(:name, :status, :cost, :day, :price, :description, :prefecture_id, :category_id, :brand, :user, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id, trading_status: 1)
  end

  def set_items
    @item = Item.find(params[:id])
  end

  def set_product
    @products = Category.where(ancestry: nil)
  end

  def set_category
    @category_parent_array = Category.where(ancestry: nil)
  end

  # 子カテゴリの一覧作成(edit,update用)
  def set_category_child
    @item = Item.find(params[:id])
    @category_children_array = @item.category.parent.parent.children
  end

  # 孫カテゴリの一覧作成(edit,update用)
  def set_category_grandchild
    @category_grandchildren_array = @item.category.parent.children
  end

  #カテゴリーデータ取得(edit,update用)
  def set_category_id
    @grandchild = @item.category
    @child = @grandchild.parent
    @parent = @child.parent
  end
end

app/views/items/_footer.html.haml
.footer
 %ul.contents
  %li.content
   %h2.content__head FURIMAについて
   %ul
    %li 
     = link_to '#' do 
      会社概要(運営会社)
    %li 
     = link_to '#' do
      プライバシーポリシー
    %li 
     = link_to '#' do
      FURIMA利用規約
    %li 
     = link_to '#' do
      ポイントに関する特約
  %li.content
   %h2.content__head FURIMAを見る
   %ul
    %li 
     = link_to '#' do
      カテゴリー一覧
    %li 
     = link_to '#' do
      ブランド一覧
  %li.content
   %h2.content__head ヘルプ&ガイド
   %ul
    %li 
     = link_to '#' do
      FURIMAガイド
    %li 
     = link_to '#' do
      FURIMAロゴ利用ガイドライン
    %li 
     = link_to '#' do
      お知らせ
     
 .footer__logo
  = link_to '#' do
   = image_tag 'logo-white.png'
 .p ©︎FURIMA

app/views/items/_form.html.haml
= render "devise/shared/header"

.furima-item
  .furima-item__input-form
    = form_for @item do |f|
      = render 'layouts/error_messages', model: f.object
      .furima-item__input-form__image
        %label.image-title
          出品画像
          %span.image-title__must
            必須
        .furima-item__input-form__image-fhoto
          ファイルを選択をクリックでアップロードできます
          .furima-item__input-form__image-fhoto__box
            .img-box-form
              - if @item.persisted?
                - @item.images.each_with_index do |image, i|
                  .img-preview
                    - if image.persisted?
                      = image_tag image.src.url, data: { index: i }, width: "120", height: '150'
                      .js-remove 
                        削除

              - if @item.new_record?
                .img-preview
                  - @item.images.each_with_index do |image, i|
                    - if image.persisted?
                      = image_tag image.src.url, data: { index: i }, width: "120", height: '150'
                      .js-remove 
                        削除

              #image-box
                %i.fas.fa-camera.camera-icon.fa-2x
                = f.fields_for :images do |image|
                  .js-file_group{"data-index": "#{image.index}"}
                    = image.file_field :src, class: 'js-file'
          
                  - if image.object.persisted?
                    = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
                      
            %hr.image-under-line
            .furima-item__input-form__description
              .furima-item__input-form__description__name
                %label.description__name__title
                  商品名
                  %span.description__name__title-must
                    必須
                = f.text_field :name, maxlength: "40", placeholder: '40文字まで',class: 'furima-item__input-form__description__name__title-input'
              .furima-item__input-form__description__text
                %label.description__text__title
                  商品の説明
                  %span.description__text__title-must
                    必須
                = f.text_area :description, maxlength: "1000", placeholder: "商品の説明（必須 1,000文字以内）", class: "furima-item__input-form__description__text__main"
            %hr.description-under-line

            .furima-item__input-form__detail
              %P.detail-concretely-title
                商品の詳細
              .furima-item__input-form__detail__category
                %label.category__title
                  カテゴリー
                  %span.category__title-must
                    必須
                .furima-item__input-form__detail__category__choose
                  - if @item.persisted?
                    / editアクションで呼び出すカテゴリ選択
                    / 親カテゴリ(初期値も設定)
                    .pulldown#partent_box
                      =f.select :category_id, options_for_select( @category_parent_array.map{|c| [c[:name], c[:id]]}, selected: @parent.id),{include_blank: "選択してください"}, { class: "parent_category_box", id: "parent_category"}
                    / 子カテゴリ(初期値およびカスタム属性data-categoryも設定)
                    .pulldown.item_input__body__category__children#children_box
                      =f.select :category_id, options_for_select( @category_children_array.map{|c| [c[:name], c[:id], {data: {category: c[:id] } }] }, selected: @child.id),{include_blank: "選択してください"}, { class: "item_input__body__category__children--select", id: "children_wrapper"}
                    / 孫カテゴリ(初期値およびカスタム属性data-categoryも設定)
                    .pulldown.item_input__body__category__grandchildren#grandchildren_box
                      =f.select :category_id, options_for_select( @category_grandchildren_array.map{|c| [c[:name], c[:id], {data: {category: c[:id] } }]}, selected: @grandchild.id),{include_blank: "選択してください"}, { class: "item_input__body__category__grandchildren--select", id: "grandchildren_wrapper"}
                  - else
                    / newアクションで呼び出すカテゴリ選択
                    / 親カテゴリ
                    .pulldown#partent_box
                      =f.select :category_id, options_for_select( @category_parent_array.map{|c| [c[:name], c[:id]]}),{include_blank: "選択してください"}, { class: "parent_category_box", id: "parent_category"}
                      / item.jsで子カテゴリを表示
                    .pulldown.item_input__body__category__children#children_box
                      / item.jsで孫カテゴリを表示
                    .pulldown.item_input__body__category__grandchildren#grandchildren_box
            
              .furima-item__input-form__detail__brand
                %label.brand__title
                  ブランド
                  %span.brand__title-any
                    任意
                = f.text_field :brand, maxlength: "40", placeholder: "例） シャネル", class:"furima-item__input-form__detail__brand__text"

              .furima-item__input-form__detail__status
                %label.status__title
                  商品の状態
                  %span.status__title-must
                    必須
                = f.select :status, Item.statuses.keys.map{ |s| [I18n.t("enums.item.status.#{s}"),s]}, {},{class: "furima-item__input-form__detail__status__choose"}
                                                      

            %hr.detail-under-line

            .furima-item__input-form__delivery
              %p.delivery-concretely-title
                配送について
              .furima-item__input-form__delivery__cost
                %label.cost__title
                  配送料の負担
                  %span.cost__title-must
                    必須
                = f.select :cost, Item.costs.keys.map{ |c| [I18n.t("enums.item.cost.#{c}"),c]}, {},{class: "furima-item__input-form__delivery__cost__choose"}
             

              .furima-item__input-form__delivery__prefecture
                %label.prefecture__title
                  発送元の地域
                  %span.prefecture__title-must
                    必須
                .furima-item__input-form__delivery__prefecture__choose
                  = f.collection_select(:prefecture_id, Prefecture.all, :id, :name,{include_blank: "選択してください"} )

              .furima-item__input-form__delivery__days
                %label.days__title
                  発送までの日数
                  %span.days__title-must
                    必須
                = f.select :day, Item.days.keys.map{ |d| [I18n.t("enums.item.day.#{d}"),d]}, {}, {class: "furima-item__input-form__delivery__days__choose"}
            %hr.delivery-under-line

            .furima-item__input-form__price
              %p.price-concretely-title
                価格 (¥300~9,999,999)
              .furima-item__input-form__price__sell
                .furima-item__input-form__price__sell__title
                  .furima-item__input-form__price__sell__title-left
                    .furima-item__input-form__price__sell__title-left-box
                      %label.sell__price
                        販売価格
                        %span.sell__price-must
                          必須
                    %span.price-mark
                      ¥

                  .furima-item__input-form__price__sell__title-right
                    = f.text_field :price, maxlength: "7", placeholder: "0", class:"furima-item__input-form__price__sell__title-right__text"
                
            .furima-item__input-form__btn
              = f.submit "出品する", class: "furima-item__input-form__btn__exhibition"
              = link_to "もどる", :back, class: "furima-item__input-form__btn__return"

            .furima-item__input-form__note
              %p.note-text
                禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律に<br>
                より処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

= render "devise/shared/footer"

app/views/items/_header.html.haml
.pcHeader
 .headerInner
  .mainHeader
   .icon
    = link_to root_path do
     = image_tag 'logo.png'
   .searchBox
    .form
     .input
     %input#searchInput.searchBox--input{name: "key", placeholder:  "キーワードから探す"}
     .button{type: 'submit'}
      .searchBox__icon
       = image_tag 'icon-search 1.png'
   .resultLists



  .nav
   %ul.listsLeft
    %li.listsLeft__itemlistsLeft__item--first
     = link_to '#' do 
      カテゴリー
    %li.listsLeft__item
     = link_to '#' do 
      ブランド
   .listsRight
   - if user_signed_in?
    .listsRight__itemlistsRight__item--login
    .listsRight__itemlistsRight__item--new
     = link_to "マイページ", user_path(current_user)
   - else
    .listsRight__itemlistsRight__item--login
     = link_to "ログイン", new_user_session_path
    .listsRight__itemlistsRight__item--new
     = link_to "新規登録", new_user_registration_path
      

app/views/items/edit.html.haml
= render "form"

app/views/items/new.html.haml
= render "form"

app/views/items/purchase.html.haml
= render "devise/shared/header"

.buy-main-header
  %h2 購入内容の確認

= render "devise/shared/footer"

app/views/items/show.html.haml
= render partial: 'header'

.main
 .showMain
  .contentLeft
  .contentRight
   .topContent
    .itemBox
     %h2.itemBox__name
      = @item.name
     .itemBox__body
      %ul
       %li
        = image_tag @item.images[0].src.url, size:'292x292'
     .itemBox__price
      .itemBox__body_sub
       - @item.images.each do |image|
        = image_tag image.src.url, size:'52x52'

      %span
       = "#{@item.price.to_s(:delimited, delimiter: ",")}"
      .itemBox__price-detail
       %span
        (税込)
       %span
        送料込み

     .itemDetail
      = @item.description

     .table
      %table
       %tbody
        %tr
         %th 出品者
         %td
          = @user.nickname
        %tr
         %th カテゴリー
         %td
          = @item.category.root.name
          %br
          = @item.category.parent.name
          %br
          = @item.category.name

        %tr
         %th ブランド
         %td
          - if @item.brand.present?
           = @item.brand
          - else
           = "---"
        %tr
         %th 商品の状態
         %td
          = @item.status_i18n
        %tr
         %th 配送料の負担
         %td
          = @item.cost_i18n
        %tr
         %th 発送元の地域
         %td 
          = @item.prefecture.name
        %tr
         %th 発送日の目安
         %td
          = @item.day_i18n

     .optionalArea
      %ul
       - if user_signed_in? && current_user.id == @item.user_id
        %li.optionalBtnlikeBtn
         = link_to edit_item_path(@item) do
          %span.purchaseBtn__text
           = icon('fas', 'edit fa-2x')
           編集する
        %li.optionalBtnlikeBtnDestroy
         = link_to item_path(@item), method: :delete do
          %span.purchaseBtn__text
           = icon('fas', 'trash-alt fa-2x')
           削除する
       - elsif @item.trading_status == "syuppintyu"
        %li.optionalBtnlikeBtn
         = link_to new_item_purchase_path(@item) do
          %span.purchaseBtn__text
           = icon('fas', 'cart-arrow-down fa-2x')
           購入する
       - else
        %li.optionalBtnsoldBtn
         = "売却済"
      %ul.optional
       %li.optionalBtn
        = link_to '' do
         = icon('fas', 'flag')
         不適切な商品の通報
%aside.appBanner
 .inner
  %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
  %p.inner__text 今すぐ無料ダウンロード！
  .inner__icon
   = link_to '#' do
    = image_tag 'app-store.svg'
   = link_to '#' do
    = image_tag 'google-play.svg'

= render partial: 'footer'