config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  get 'users/:id/logout', to: 'users#logout'

  resources :users, only: [:show]
  resources :cards, only: [:new, :create, :destroy, :show]

  root to: 'messages#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: [:new, :create]
  end
end

app/models/card.rb
class Card < ApplicationRecord
  validates :user_id, :customer_id, :card_id, presence: true
  validates :user_id, uniqueness: true

  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card

  def index
  end

  def new
    @card = Card.new
    redirect_to card_path(current_user.id) if @card.nil?
  end

  def create
    Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
    if params['payjp_token'].blank?
      redirect_to action: "new", alert: 'クレジットカードを登録してください'
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp_token"],
        metadata: {user_id: current_user.id }
      )
      @card =  Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show", id: current_user.id
      else
        render "new", alert: 'クレジットカード情報が正しくありません'
      end
    end
  end

  def show
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
    end
    
  end

  def destroy
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      if @card.destroy
        redirect_to user_path(current_user.id), notice: "削除しました。"
      else
        redirect_to card_path(current_user.id), alert: "削除できませんでした。"
      end
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end
end

app/views/cards/create.html.haml
= render "items/header"
%main.content
  %section.content-credit
    .content-credit__message
      登録が完了しました
    %ul.content-credit__btns
      %li.my_page_link
        = link_to "マイページに戻る", users_path(current_user.id)
      %li.credit_cards_index_link
      = link_to "登録カード一覧", card_path(current_user.id)


.main
  %section.mainBanner
    .inner
      %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text 今すぐ無料ダウンロード！
      .inner__icon
        = link_to image_tag("pict/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"aBtn"), "/"
        = link_to image_tag("pict/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"gBtn"), "/"
= render "items/footer"

app/views/cards/new.html.haml
= render "items/header"
%main.content
  %section.content-credit
    %h2.content-credit__title
      クレジットカード情報入力
    = form_tag(cards_path, method: :post, id: "card", class: "content-credit__form", name: "inputForm") do |f|
      .content-credit__form__number
        %label カード番号
        %span.check 必須
        = text_field_tag "number", "", class: "content-credit__form__number__input", type: "text", maxlength: "16", placeholder: "例)1234567891234567"
      .content-credit__form__days
        %label 有効期限
        %span.check 必須
        .content-credit__form__days__deadline
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          .content-credit__form__days__deadline__month
            月
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
            %option{value: "2030"}30
          .content-credit__form__days__deadline__year
            年
      .content-credit__form__security
        .content-credit__form__security__title
          %label セキュリティーコード
          %span.check 必須
        .content-credit__form__security__code
          = text_field_tag "cvc", "", class: "content-credit__form__security__code__input", type: "text", id: "cvc", maxlength: "4", placeholder: "例)1234"
      .content-credit__form__btn
        #card_token
          = submit_tag "登録", class: "content-credit__form__btn__submit", id: "token_submit", type: 'button'
  .content-bottom
    %nav.mypage-menuy 
      設定
      %ul.mypage-menuy__list
        %li 
          = link_to "マイページ", user_path(current_user)
        %li
          = link_to "ログアウト", "/users/:id/logout"
.main
  %section.mainBanner
    .inner
      %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text 今すぐ無料ダウンロード！
      .inner__icon
        = link_to image_tag("pict/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"aBtn"), "/"
        = link_to image_tag("pict/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"gBtn"), "/"
= render "items/footer"

app/views/cards/show.html.haml
= render "items/header"
%main.content
  %section.content-card
    %h2.content-card__title
      登録クレジットカード情報
    .content-card__list
      %h3.content-card__list__title
        クレジットカード一覧
      .credit-info
        .credit-info__numbers
          %p.credit-info__numbers__card
            = "**** **** ****" + @customer_card.last4
          %ul.expiration_date
            %li.expiration_date__title
              有効期限
            %li.expiration_date__info
              = @exp_month + "/" + @exp_year
      .destroy__function
        = link_to "削除する", card_path, method: :delete, class: "destroy__function__link" 
  .content-bottom
    %nav.mypage-menuy 
      設定
      %ul.mypage-menuy__list
        %li 
          = link_to "マイページ", user_path(current_user)
        %li
          = link_to "ログアウト", "/users/:id/logout"
.main
  %section.mainBanner
    .inner
      %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text 今すぐ無料ダウンロード！
      .inner__icon
        = link_to image_tag("pict/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"aBtn"), "/"
        = link_to image_tag("pict/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"gBtn"), "/"
= render "items/footer"